server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://vcs-service-db.cf08d3xfd2vx.ap-northeast-2.rds.amazonaws.com:3306/vcsDB
    username: user
    password: team4-user

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug

serviceKey: e08f7MGVA9XkHa7TejMnVUyzblYcfPQy

